
services:
  postgres:
    image: postgres:16
    container_name: interview-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: interview_user_official
      POSTGRES_PASSWORD: Harshal0508
      POSTGRES_DB: interview_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U interview_user_official -d interview_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend

    container_name: interview-backend

    restart: unless-stopped

    env_file:
      - ./backend/.env

    ports:
      - "8000:8000"

    depends_on:
      postgres:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  frontend:
    build:
      context: ./frontend
      args:
        VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}
    container_name: interview-frontend

    restart: unless-stopped

    ports:
      - "3000:80"

    depends_on:
      backend:
        condition: service_healthy

volumes:
  postgres_data: