export const TERMS_LAST_UPDATED = "August 30, 2026";

export const TERMS_SECTIONS = [
  {
    heading: "1. Acceptance of Terms",
    body: 'By creating an account and using Hot Seat ("the Service", "we", "us"), you agree to these Terms & Conditions. If you do not agree, do not use the Service.',
  },
  {
    heading: "2. What Hot Seat Is",
    body: "Hot Seat is an AI-assisted interview preparation tool. It generates practice interview questions, evaluates your answers, analyzes your resume against job descriptions, and — if you opt in — analyzes your voice/camera delivery during practice. Questions, feedback, scores, and resume analysis are generated by AI models (including Google Gemini) and are provided for practice purposes only.",
  },
  {
    heading: "3. Not Professional Advice / No Guaranteed Outcomes",
    body: "AI-generated feedback, scores, ATS match percentages, and suggestions are automated estimates, not guarantees. They may be incomplete or inaccurate. Hot Seat does not guarantee that using the Service will result in a job offer, interview invitation, or any specific outcome, and is not a substitute for professional career, legal, or HR advice.",
  },
  {
    heading: "4. Your Account",
    body: "You must provide accurate information when creating your account and completing your profile. You are responsible for keeping your login credentials secure and for all activity under your account. You must be at least 16 years old to use Hot Seat.",
  },
  {
    heading: "5. Your Content",
    body: 'You retain ownership of the resumes, job descriptions, answers, and profile information you submit ("Your Content"). By submitting Your Content, you grant Hot Seat a license to process it — including sending it to third-party AI providers such as Google Gemini — solely to provide the Service to you. Do not upload anyone else\'s personal data without permission, or any unlawful, infringing, or malicious content.',
  },
  {
    heading: "6. Camera & Microphone (Delivery Analysis)",
    body: "If you opt in to delivery analysis during a practice interview, Hot Seat may access your camera and/or microphone to compute delivery signals (pause count, pacing, eye contact). Your raw audio/video is processed in your browser and is not recorded or uploaded — only derived summary metrics are used. You can decline this at any time; declining does not block the rest of the Service.",
  },
  {
    heading: "7. Third-Party Services",
    body: "Hot Seat relies on third-party providers to operate, including Google Gemini (AI generation/evaluation), Google OAuth (sign-in), and Brevo (transactional email). Your use of the Service is also subject to those providers' own terms where applicable.",
  },
  {
    heading: "8. Prohibited Use",
    body: "Do not: use the Service to generate or submit unlawful, hateful, or harmful content; attempt to reverse-engineer, scrape, or overload the Service; use another person's account without authorization; or try to circumvent usage limits or security controls.",
  },
  {
    heading: "9. Code Execution Feature",
    body: "Code submitted through Hot Seat's coding-practice feature is executed in a sandboxed environment for evaluation only. Do not submit malicious code or attempt to access, exfiltrate, or interfere with system resources, other users' data, or the underlying infrastructure.",
  },
  {
    heading: "10. Service Availability",
    body: 'Hot Seat is provided "as is" and "as available." We may modify, suspend, or discontinue any part of the Service at any time and do not guarantee uninterrupted or error-free operation.',
  },
  {
    heading: "11. Limitation of Liability",
    body: "To the fullest extent permitted by law, Hot Seat and its operators are not liable for indirect, incidental, or consequential damages arising from your use of the Service, including reliance on AI-generated feedback or any interview/job outcome.",
  },
  {
    heading: "12. Termination",
    body: "We may suspend or terminate accounts that violate these Terms. You may stop using the Service and request account/data deletion at any time by contacting us.",
  },
  {
    heading: "13. Changes to These Terms",
    body: "We may update these Terms from time to time. Continued use of the Service after changes take effect means you accept the revised Terms.",
  },
  {
    heading: "14. Contact",
    body: "Questions about these Terms? Contact us at harshal05shah@gmail.com.",
  },
];
